# Validerer kodekvalitet for konsistens (pylint) og funktionalitet (pytest)

name: lint-og-test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    kodevalidering:
        name: valider på ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        
        steps:
            - name: projekt-repo checkout til runner
              uses: actions/checkout@v4

            - name: python set-up
              uses: actions/setup-python@v5
              with:
                python-version: "3.9"

            - name: installere requirements.txt
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: kør pylint
              run: |
                pylint src/ || exit 0

            - name: kør pytest
              run: |
                pytest tests/

